-- =============================================================================
-- Motiva — Sprint 3
-- Dados de teste baseados no CatalogoRodovias da Sprint 2
-- (BR-101, BR-116, BR-381 — 8 trechos + 3 equipes + intervenções)
-- =============================================================================

-- Equipes alinhadas aos tipos de intervenção da Sprint 2
INSERT INTO T_MOTIVA_EQUIPE_MANUTENCAO (
    ID_EQUIPE, NM_EQUIPE, DS_ESPECIALIDADE, QT_MEMBROS, DS_BASE_OPERACIONAL, ST_DISPONIVEL
) VALUES (SEQ_MOTIVA_EQUIPE.NEXTVAL, 'Equipe Alpha — Roçadeira', 'ROCADA_MECANIZADA', 6, 'Base Serra — BR-116', 'S');

INSERT INTO T_MOTIVA_EQUIPE_MANUTENCAO (
    ID_EQUIPE, NM_EQUIPE, DS_ESPECIALIDADE, QT_MEMBROS, DS_BASE_OPERACIONAL, ST_DISPONIVEL
) VALUES (SEQ_MOTIVA_EQUIPE.NEXTVAL, 'Equipe Beta — Encosta', 'ROCADA_MANUAL', 4, 'Base Litoral — BR-101', 'S');

INSERT INTO T_MOTIVA_EQUIPE_MANUTENCAO (
    ID_EQUIPE, NM_EQUIPE, DS_ESPECIALIDADE, QT_MEMBROS, DS_BASE_OPERACIONAL, ST_DISPONIVEL
) VALUES (SEQ_MOTIVA_EQUIPE.NEXTVAL, 'Equipe Gama — Invasoras', 'PULVERIZACAO', 3, 'Base Vale — BR-381', 'S');

-- Trechos do cenário de demonstração (CatalogoRodovias)
INSERT INTO T_MOTIVA_TRECHO_RODOVIA (
    ID_TRECHO, DS_RODOVIA, NR_KM, NR_ALTURA_VEGETACAO, DS_TIPO_TERRENO,
    ST_ACESSO_DIFICIL, ST_INFESTACAO_INVASORA, QT_DIAS_SEM_MANUTENCAO,
    ST_MONITORADO_IOT, NR_LEITURA_SENSOR, ID_EQUIPE_RESPONSAVEL
) VALUES (SEQ_MOTIVA_TRECHO.NEXTVAL, 'BR-101', 412, 0.85, 'SECO', 'N', 'N', 22, 'N', NULL, 1);

INSERT INTO T_MOTIVA_TRECHO_RODOVIA (
    ID_TRECHO, DS_RODOVIA, NR_KM, NR_ALTURA_VEGETACAO, DS_TIPO_TERRENO,
    ST_ACESSO_DIFICIL, ST_INFESTACAO_INVASORA, QT_DIAS_SEM_MANUTENCAO,
    ST_MONITORADO_IOT, NR_LEITURA_SENSOR, ID_EQUIPE_RESPONSAVEL
) VALUES (SEQ_MOTIVA_TRECHO.NEXTVAL, 'BR-101', 413, 1.05, 'UMIDO', 'N', 'N', 38, 'N', NULL, 1);

INSERT INTO T_MOTIVA_TRECHO_RODOVIA (
    ID_TRECHO, DS_RODOVIA, NR_KM, NR_ALTURA_VEGETACAO, DS_TIPO_TERRENO,
    ST_ACESSO_DIFICIL, ST_INFESTACAO_INVASORA, QT_DIAS_SEM_MANUTENCAO,
    ST_MONITORADO_IOT, NR_LEITURA_SENSOR, ID_EQUIPE_RESPONSAVEL
) VALUES (SEQ_MOTIVA_TRECHO.NEXTVAL, 'BR-101', 414, 0.95, 'UMIDO', 'S', 'N', 41, 'N', NULL, 2);

INSERT INTO T_MOTIVA_TRECHO_RODOVIA (
    ID_TRECHO, DS_RODOVIA, NR_KM, NR_ALTURA_VEGETACAO, DS_TIPO_TERRENO,
    ST_ACESSO_DIFICIL, ST_INFESTACAO_INVASORA, QT_DIAS_SEM_MANUTENCAO,
    ST_MONITORADO_IOT, NR_LEITURA_SENSOR, ID_EQUIPE_RESPONSAVEL
) VALUES (SEQ_MOTIVA_TRECHO.NEXTVAL, 'BR-116', 78, 1.15, 'ROCHOSO', 'S', 'N', 52, 'N', NULL, 2);

INSERT INTO T_MOTIVA_TRECHO_RODOVIA (
    ID_TRECHO, DS_RODOVIA, NR_KM, NR_ALTURA_VEGETACAO, DS_TIPO_TERRENO,
    ST_ACESSO_DIFICIL, ST_INFESTACAO_INVASORA, QT_DIAS_SEM_MANUTENCAO,
    ST_MONITORADO_IOT, NR_LEITURA_SENSOR, ID_EQUIPE_RESPONSAVEL
) VALUES (SEQ_MOTIVA_TRECHO.NEXTVAL, 'BR-116', 79, 0.70, 'SECO', 'N', 'S', 60, 'S', 1.28, 3);

INSERT INTO T_MOTIVA_TRECHO_RODOVIA (
    ID_TRECHO, DS_RODOVIA, NR_KM, NR_ALTURA_VEGETACAO, DS_TIPO_TERRENO,
    ST_ACESSO_DIFICIL, ST_INFESTACAO_INVASORA, QT_DIAS_SEM_MANUTENCAO,
    ST_MONITORADO_IOT, NR_LEITURA_SENSOR, ID_EQUIPE_RESPONSAVEL
) VALUES (SEQ_MOTIVA_TRECHO.NEXTVAL, 'BR-381', 505, 0.60, 'SECO', 'N', 'S', 15, 'N', NULL, 3);

INSERT INTO T_MOTIVA_TRECHO_RODOVIA (
    ID_TRECHO, DS_RODOVIA, NR_KM, NR_ALTURA_VEGETACAO, DS_TIPO_TERRENO,
    ST_ACESSO_DIFICIL, ST_INFESTACAO_INVASORA, QT_DIAS_SEM_MANUTENCAO,
    ST_MONITORADO_IOT, NR_LEITURA_SENSOR, ID_EQUIPE_RESPONSAVEL
) VALUES (SEQ_MOTIVA_TRECHO.NEXTVAL, 'BR-381', 506, 1.00, 'UMIDO', 'N', 'N', 33, 'S', 1.18, 1);

INSERT INTO T_MOTIVA_TRECHO_RODOVIA (
    ID_TRECHO, DS_RODOVIA, NR_KM, NR_ALTURA_VEGETACAO, DS_TIPO_TERRENO,
    ST_ACESSO_DIFICIL, ST_INFESTACAO_INVASORA, QT_DIAS_SEM_MANUTENCAO,
    ST_MONITORADO_IOT, NR_LEITURA_SENSOR, ID_EQUIPE_RESPONSAVEL
) VALUES (SEQ_MOTIVA_TRECHO.NEXTVAL, 'BR-381', 507, 1.35, 'SECO', 'N', 'N', 8, 'N', NULL, 1);

-- Intervenções de exemplo (pendente / executada)
INSERT INTO T_MOTIVA_INTERVENCAO (
    ID_INTERVENCAO, ID_TRECHO, ID_EQUIPE, DS_TIPO, ST_INTERVENCAO,
    DT_AGENDADA, NR_ALTURA_ANTES, NR_ALTURA_DEPOIS, DS_OBSERVACAO
) VALUES (
    SEQ_MOTIVA_INTERVENCAO.NEXTVAL, 4, 2, 'ROCADA_MANUAL', 'PENDENTE',
    SYSDATE + 1, 1.15, NULL, 'Encosta rochosa da BR-116 KM 78 — acesso restrito'
);

INSERT INTO T_MOTIVA_INTERVENCAO (
    ID_INTERVENCAO, ID_TRECHO, ID_EQUIPE, DS_TIPO, ST_INTERVENCAO,
    DT_AGENDADA, NR_ALTURA_ANTES, NR_ALTURA_DEPOIS, DS_OBSERVACAO
) VALUES (
    SEQ_MOTIVA_INTERVENCAO.NEXTVAL, 5, 3, 'PULVERIZACAO', 'PENDENTE',
    SYSDATE, 1.28, NULL, 'Sensor IoT detectou invasoras acima do limite'
);

INSERT INTO T_MOTIVA_INTERVENCAO (
    ID_INTERVENCAO, ID_TRECHO, ID_EQUIPE, DS_TIPO, ST_INTERVENCAO,
    DT_AGENDADA, NR_ALTURA_ANTES, NR_ALTURA_DEPOIS, DS_OBSERVACAO
) VALUES (
    SEQ_MOTIVA_INTERVENCAO.NEXTVAL, 8, 1, 'ROCADA_MECANIZADA', 'EXECUTADA',
    SYSDATE - 2, 1.50, 0.30, 'Roçada mecanizada concluída na BR-381 KM 507'
);

-- Relatório histórico de exemplo
INSERT INTO T_MOTIVA_RELATORIO_PRIORIDADE (
    ID_RELATORIO, DT_GERACAO, QT_URGENTE, QT_CRITICO, QT_ATENCAO, QT_NORMAL, DS_RESUMO
) VALUES (
    SEQ_MOTIVA_RELATORIO.NEXTVAL,
    SYSTIMESTAMP,
    1, 1, 2, 4,
    'Carga inicial: 8 trechos do CatalogoRodovias. Urgente: BR-116 KM 79 (IoT + invasoras).'
);

COMMIT;
