-- =============================================================================
-- Motiva — Sprint 3
-- Script de CRIAÇÃO das tabelas a partir das classes da Sprint 1/2
--
-- Mapeamento:
--   EquipeManutencao      -> T_MOTIVA_EQUIPE_MANUTENCAO   (nova entidade operacional)
--   TrechoRodovia         -> T_MOTIVA_TRECHO_RODOVIA      (domain.TrechoRodovia)
--   IntervencaoOperacional-> T_MOTIVA_INTERVENCAO         (hierarquia Rocada/Pulverizacao)
--   RelatorioPrioridade   -> T_MOTIVA_RELATORIO_PRIORIDADE (histórico do GeradorRelatorio)
-- =============================================================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_MOTIVA_RELATORIO_PRIORIDADE CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_MOTIVA_INTERVENCAO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_MOTIVA_TRECHO_RODOVIA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_MOTIVA_EQUIPE_MANUTENCAO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MOTIVA_EQUIPE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MOTIVA_TRECHO';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MOTIVA_INTERVENCAO';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MOTIVA_RELATORIO';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

CREATE SEQUENCE SEQ_MOTIVA_EQUIPE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MOTIVA_TRECHO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MOTIVA_INTERVENCAO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MOTIVA_RELATORIO START WITH 1 INCREMENT BY 1 NOCACHE;

-- Equipes que executam as intervenções (Roçada Mecanizada, Manual ou Pulverização)
CREATE TABLE T_MOTIVA_EQUIPE_MANUTENCAO (
    ID_EQUIPE            NUMBER         PRIMARY KEY,
    NM_EQUIPE            VARCHAR2(80)   NOT NULL,
    DS_ESPECIALIDADE     VARCHAR2(40)   NOT NULL,
    QT_MEMBROS           NUMBER(3)      NOT NULL,
    DS_BASE_OPERACIONAL  VARCHAR2(80)   NOT NULL,
    ST_DISPONIVEL        CHAR(1)        DEFAULT 'S' NOT NULL,
    CONSTRAINT CK_MOTIVA_EQUIPE_DISP CHECK (ST_DISPONIVEL IN ('S', 'N')),
    CONSTRAINT CK_MOTIVA_EQUIPE_ESP  CHECK (DS_ESPECIALIDADE IN ('ROCADA_MECANIZADA', 'ROCADA_MANUAL', 'PULVERIZACAO')),
    CONSTRAINT CK_MOTIVA_EQUIPE_QT   CHECK (QT_MEMBROS > 0)
);

-- Trechos das rodovias (atributos de TrechoRodovia + flag IoT de TrechoRodoviaMonitorado)
CREATE TABLE T_MOTIVA_TRECHO_RODOVIA (
    ID_TRECHO              NUMBER         PRIMARY KEY,
    DS_RODOVIA             VARCHAR2(20)   NOT NULL,
    NR_KM                  NUMBER(6)      NOT NULL,
    NR_ALTURA_VEGETACAO    NUMBER(5,2)    NOT NULL,
    DS_TIPO_TERRENO        VARCHAR2(20)   NOT NULL,
    ST_ACESSO_DIFICIL      CHAR(1)        DEFAULT 'N' NOT NULL,
    ST_INFESTACAO_INVASORA CHAR(1)        DEFAULT 'N' NOT NULL,
    QT_DIAS_SEM_MANUTENCAO NUMBER(5)      DEFAULT 0 NOT NULL,
    ST_MONITORADO_IOT      CHAR(1)        DEFAULT 'N' NOT NULL,
    NR_LEITURA_SENSOR      NUMBER(5,2),
    ID_EQUIPE_RESPONSAVEL  NUMBER,
    CONSTRAINT CK_MOTIVA_TRECHO_TERRENO  CHECK (DS_TIPO_TERRENO IN ('UMIDO', 'SECO', 'ROCHOSO')),
    CONSTRAINT CK_MOTIVA_TRECHO_ACESSO   CHECK (ST_ACESSO_DIFICIL IN ('S', 'N')),
    CONSTRAINT CK_MOTIVA_TRECHO_INVASORA CHECK (ST_INFESTACAO_INVASORA IN ('S', 'N')),
    CONSTRAINT CK_MOTIVA_TRECHO_IOT      CHECK (ST_MONITORADO_IOT IN ('S', 'N')),
    CONSTRAINT CK_MOTIVA_TRECHO_ALTURA   CHECK (NR_ALTURA_VEGETACAO >= 0),
    CONSTRAINT UN_MOTIVA_TRECHO_KM       UNIQUE (DS_RODOVIA, NR_KM),
    CONSTRAINT FK_MOTIVA_TRECHO_EQUIPE   FOREIGN KEY (ID_EQUIPE_RESPONSAVEL)
        REFERENCES T_MOTIVA_EQUIPE_MANUTENCAO (ID_EQUIPE)
);

-- Intervenção operacional persistida (tipo = classe concreta da Sprint 2)
CREATE TABLE T_MOTIVA_INTERVENCAO (
    ID_INTERVENCAO   NUMBER         PRIMARY KEY,
    ID_TRECHO        NUMBER         NOT NULL,
    ID_EQUIPE        NUMBER         NOT NULL,
    DS_TIPO          VARCHAR2(40)   NOT NULL,
    ST_INTERVENCAO   VARCHAR2(20)   DEFAULT 'PENDENTE' NOT NULL,
    DT_AGENDADA      DATE           NOT NULL,
    NR_ALTURA_ANTES  NUMBER(5,2),
    NR_ALTURA_DEPOIS NUMBER(5,2),
    DS_OBSERVACAO    VARCHAR2(255),
    CONSTRAINT CK_MOTIVA_INT_TIPO   CHECK (DS_TIPO IN ('ROCADA_MECANIZADA', 'ROCADA_MANUAL', 'PULVERIZACAO')),
    CONSTRAINT CK_MOTIVA_INT_STATUS CHECK (ST_INTERVENCAO IN ('PENDENTE', 'EXECUTADA', 'CANCELADA')),
    CONSTRAINT FK_MOTIVA_INT_TRECHO FOREIGN KEY (ID_TRECHO)
        REFERENCES T_MOTIVA_TRECHO_RODOVIA (ID_TRECHO),
    CONSTRAINT FK_MOTIVA_INT_EQUIPE FOREIGN KEY (ID_EQUIPE)
        REFERENCES T_MOTIVA_EQUIPE_MANUTENCAO (ID_EQUIPE)
);

-- Histórico dos relatórios gerados pelo GeradorRelatorio
CREATE TABLE T_MOTIVA_RELATORIO_PRIORIDADE (
    ID_RELATORIO NUMBER         PRIMARY KEY,
    DT_GERACAO   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    QT_URGENTE   NUMBER(5)      DEFAULT 0 NOT NULL,
    QT_CRITICO   NUMBER(5)      DEFAULT 0 NOT NULL,
    QT_ATENCAO   NUMBER(5)      DEFAULT 0 NOT NULL,
    QT_NORMAL    NUMBER(5)      DEFAULT 0 NOT NULL,
    DS_RESUMO    VARCHAR2(1000) NOT NULL
);

COMMIT;
